build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=build/coverage/frontend.xml protected/tests/unit/
                coverage:
                    file: build/coverage/frontend.xml
                    format: php-clover
