build:
    tests:
        override:
            -
                command: phpunit --coverage-clover=build/coverage/frontend.xml -c protected/tests/coverage.xml protected/tests/unit/
                command: phpunit --coverage-clover=build/coverage/backend.xml -c backend/protected/tests/coverage.xml backend/protected/tests/unit/
                coverage:
                    file: build/coverage/
                    format: php-clover
