language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
#  - hhvm
#  - hhvm-nightly

services:
  - mysql

#before_install:
#  - pear channel-discover pear.phing.info
#  - pear install phing/phing
#  - phpenv rehash

install:
  - cd .. && git clone https://github.com/yiisoft/yii.git yii
  - cd yii && git checkout 2e702fa83a64b6417addebf485ab6af9dabc1dfe
  - cd ../argilla-test-travis
  - wget http://www.phing.info/get/phing-latest.phar
  - chmod +x phing-latest.phar
  - sudo mv phing-latest.phar phing.phar
#  - wget https://phar.phpunit.de/phpunit-3.7.38.phar
#  - chmod +x phpunit-3.7.38.phar
#  - sudo mv phpunit-3.7.38.phar phpunit.phar

before_script:
  - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'prog'@'localhost' IDENTIFIED BY '123' WITH GRANT OPTION;" -uroot
  - php phing.phar bootstrap -DdbName=argilla -DdbTablePrefix=argilla_ -DdbUser=prog -DdbPassword=123 -Dconfirm=y -DconfirmTest=y

script:
  - phpunit -c backend/protected/tests/phpunit.xml backend/protected/tests/unit/
  - phpunit -c protected/tests/phpunit.xml protected/tests/unit/
